(setq elfeed-feeds
      '(("https://xkcd.com/rss.xml" comic)
         ("https://blog.rstudio.com/index.xml" R prog)
         ("https://rviews.rstudio.com/index.xml" R prog)
         ("http://planet.emacsen.org/atom.xml" emacs)
         ("http://feeds.nature.com/nclimate/rss/current" HI)
         ("http://feeds.nature.com/ncomms/rss/current" HI)
         ("http://feeds.nature.com/nature/rss/current" HI)
         ("http://feeds.nature.com/natecolevol/rss/current" HI)
         ("http://feeds.nature.com/nplants/rss/current?format=xml" HI)
         ("http://feeds.nature.com/srep/rss/current" HI)
         ("http://science.sciencemag.org/rss/current.xml" HI)
         ("http://advances.sciencemag.org/rss/current.xml" HI)
         ("http://rss.sciencedirect.com/publication/science/11257865")
         ("http://www.biogeosciences.net/xml/ss2_0.xml" biogeo)
         ("http://rss.sciencedirect.com/publication/science/5934")
         ("https://esajournals.onlinelibrary.wiley.com/action/showFeed?jc=19399170&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=14610248&type=etoc&feed=rss")
         ("http://feeds.feedburner.com/EnvironmentalResearchLettersLatestPapers?format=xml")
         ("http://rss.sciencedirect.com/publication/science/5042")
         ("https://www.frontiersin.org/journals/plant-science/rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=13652435&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=13652486&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=14668238&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=13652745&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=16000706&type=etoc&feed=rss")
         ("https://onlinelibrary.wiley.com/action/showFeed?jc=14698137&type=etoc&feed=rss")
         ("https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=468&channel-name=Trees")
         ("https://academic.oup.com/rss/site_5247/3115.xml")))

