My configuration file for [[https://www.gnu.org/software/emacs/][Emacs]].

* General

Enable trashing of files from dired on macOS.

#+BEGIN_SRC sh
brew install trash
#+END_SRC

* Org

Get more recent org-mode from MELPA like this

#+BEGIN_SRC sh
emacs -Q -batch -eval "(progn (require 'package) (add-to-list 'package-archives '(\"org\" . \"http://orgmode.org/elpa/\"))  (package-initialize) (package-refresh-contents) (package-install 'org-plus-contrib))"
#+END_SRC

Org-babel support for Julia is added via ob-julia.el. This uses an
external repository:

#+begin_src sh
git clone https://github.com/gjkerns/ob-julia.git ~/lisp/ob-julia
#+end_src

* Spellchecking

Spell checking is done using =aspell= which has to be installed
separately. On OS X:

#+begin_src sh
  brew install aspell --with-lang-de --with-lang-en
#+end_src

* Dictionary

  Install and use Webster's dictionary.

#+BEGIN_SRC sh
  brew install sdcv
  mkdir -p ~/.stardict/dic/
  wget https://s3.amazonaws.com/jsomers/dictionary.zip
  unzip dictionary.zip
  cd dictionary
  tar jxf stardict-dictd-web1913-2.4.2.tar.bz2
  mv stardict-dictd-web1913-2.4.2/* ~/.stardict/dic/
#+END_SRC

  with point on word, do =M-x sdcv-search=

* ESS

[[http://ess.r-project.org][ESS]] is installed as described in the [[http://ess.r-project.org][instructions]], and not from MELPA!

So, this is:

#+begin_src sh
git clone https://github.com/emacs-ess/ESS.git ~/lisp/ess
#+end_src

Then, checkout appropriate tag, if wanted.

* ycmd

Install daemon and build for C++ support:

#+begin_src sh
git clone https://github.com/Valloric/ycmd.git ~/lisp/ycmd
cd ~/lisp/ycmd
git submodule update --init --recursive
./build.py --clang-completer
#+end_src

Use additional config per project: install =YCM-Generator= and run
=./config_gen.py <PROJECTBASEPATH>= to generate extra
=.ycm_extra_conf.py=.

* Rtags

  Open Emacs and do =M-x rtags-install=. Depending on =rtags= version,
  customise =rtags-path= to =~/.emacs.d/rtags-VERSION/bin=.

  To use with project, run =cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .=
  in source directory.

* Synctex

We also need in =~/.latexmkrc=:

#+begin_src
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$pdf_previewer = 'open -a skim';
$clean_ext = 'bbl rel %R-blx.bib %R.synctex.gz';
#+end_src
* Elpy

#+begin_src sh
pip install jedi flake8 autopep8

#+end_src
* LilyPond

#+BEGIN_SRC bash
brew cask install lilypond
#+END_SRC
