(diminish 'auto-fill-function " af")
(diminish 'visual-line-mode)
(diminish 'ivy-mode)
(diminish 'beacon-mode)
(defun cz-ess-diminish-modes ()
  (diminish 'smartparens-mode)
  (diminish 'eldoc-mode))
(add-hook 'ess-mode-hook 'cz-ess-diminish-modes)
(provide 'init-diminish)
