(setq elfeed-feeds
      '("http://www.blog.lehren.tum.de/feed/"
        "http://planet.emacsen.org/atom.xml"
        "https://posteo.de/blog/feed?format=atom"
        "https://www.r-users.com/feed/?rss_featured=1"
        "http://www.win-vector.com/blog/feed/"
        "http://feeds.feedburner.com/RBloggers?format=xml"
        "https://usesthis.com/feed/"
        "https://github.com/blog/all.atom"
        "https://rweekly.org/atom.xml"
        "https://blog.rstudio.org/feed/"
        "http://www.biogeosciences.net/xml/rss2_0.xml"
        "http://www.cell.com/trends/ecology-evolution/inpress.rss"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1600-0706"
        "http://feeds.nature.com/nplants/rss/current?format=xml"
        "http://feeds.nature.com/nclimate/rss/current"
        "http://feeds.nature.com/nature/rss/current"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1365-2745"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1466-8238"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1365-2486"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1365-2435"
        "http://journal.frontiersin.org/journal/plant-science/rss"
        "http://rss.sciencedirect.com/publication/science/5042"
        "http://feeds.feedburner.com/EnvironmentalResearchLettersLatestPapers?format=xml"
        "http://rss.sciencedirect.com/publication/science/5934"
        "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1600-0587"))

(provide 'init-elfeed)
